# Builds the program for multiple targets and then creates a GitHub release containing
# the resulting files. This uses the body of the
# annotated tag (git tag -a) to populate the body of the release.

name: release
env:
  # The name of the program executable.
  PROGRAM_NAME: smeagol-wiki
on:
  push:
    # Enable when testing release infrastructure on a branch.
    # branches:
    # - ci_testing
    tags:
      # Despite their appearance, these are NOT regular expressions =(
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*" # prerelease
jobs:

  build-release:
    permissions: {}
    runs-on: ${{ matrix.image }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        include:
          - build: linux-x64
            os: ubuntu
            image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - build: linux-arm32
            os: ubuntu
            image: ubuntu-24.04
            target: arm-unknown-linux-gnueabihf
            use-cross: true
          - build: linux-arm64
            os: ubuntu
            image: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - build: macos-x64
            os: macos
            image: macos-26
            target: x86_64-apple-darwin
            use-cross: false
          - build: macos-arm64
            os: macos
            image: macos-26
            target: aarch64-apple-darwin
            use-cross: false
          - build: win-x64-msvc
            os: windows
            image: windows-2025
            target: x86_64-pc-windows-msvc
            use-cross: false
          - build: win-x86-msvc
            os: windows
            image: windows-2025
            target: i686-pc-windows-msvc
            use-cross: false
          - build: win-arm64-msvc
            os: windows
            image: windows-2025
            target: aarch64-pc-windows-msvc
            use-cross: false

    steps:

      # NOTE NOTE NOTE NOTE NOTE NOTE
      #
      # See .cargo/config.toml for an explanation of these settings.
      # Keep these settings and that file in sync.
      #
      # NOTE NOTE NOTE NOTE NOTE NOTE
      - name: Rust Flags
        shell: bash
        if: matrix.os == 'windows'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static -C link-arg=/DEPENDENTLOADFLAG:0x800" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build with Cross
        if: matrix.use-cross
        run: |
          mkdir "$HOME/cross"
          curl -o "$HOME/cross/cross.tar.gz" -sSL "https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz"
          echo "536cf0ced0bf97a747ae2dae3f625bd243f277fc61298d91c80b8ee04e2f8f6303028d61324964b33e666311424bc199708153236ab59e9d99ee550408cc6df0  $HOME/cross/cross.tar.gz" | shasum -a 512 --strict -c -
          tar -C "$HOME/cross" -xzf "$HOME/cross/cross.tar.gz"
          "$HOME/cross/cross" build --release --target ${{ matrix.target }}

      - name: Build with Cargo
        if: '!matrix.use-cross'
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

      - name: Strip release binary (macos)
        if: matrix.os == 'macos'
        run: strip "target/${{ matrix.target }}/release/${{ env.PROGRAM_NAME }}"

      - name: Build archive
        shell: bash
        run: |
          staging="${PROGRAM_NAME}-${{ github.ref_name }}-${{ matrix.target }}"
          mkdir -p "$staging"/doc

          cp {README.md,LICENSE} "$staging/"
          cp CHANGELOG.md "$staging/doc/"

          if [ "${{ matrix.os }}" = "windows" ]; then
            cp "target/${{ matrix.target }}/release/${PROGRAM_NAME}.exe" "$staging/"
            7z a "$staging.zip" "$staging"
            certutil -hashfile "$staging.zip" SHA512 > "$staging.zip.sha512"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp "target/${{ matrix.target }}/release/${PROGRAM_NAME}" "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            shasum -a 512 "$staging.tar.gz" > "$staging.tar.gz.sha512"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload Output
        uses: actions/upload-artifact@v7
        with:
          retention-days: 7
          if-no-files-found: error
          archive: false
          path: ${{ env.ASSET }}

      - name: Upload Output
        uses: actions/upload-artifact@v7
        with:
          retention-days: 7
          if-no-files-found: error
          archive: false
          path: ${{ env.ASSET }}.sha512

  publish-release:
    permissions:
      contents: write
    needs: ["build-release"]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create temp directory
        id: create-temp-dir
        run: |
          mkdir "$HOME/artifacts"
          echo "dir=$HOME/artifacts" >> $GITHUB_OUTPUT

      - name: Download built programs and symbols
        uses: actions/download-artifact@v8
        with:
          path: ${{ steps.create-temp-dir.outputs.dir }}
          merge-multiple: true

      - name: List artifacts
        run: ls -l $HOME/artifacts

      - name: Create release
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --draft --notes-from-tag --verify-tag \
            ${{ contains(github.ref_name, '-') && '--prerelease' || '' }} \
            $HOME/artifacts/*
